<a href="https://colab.research.google.com/github/Resia05/supervised-learning/blob/main/%D0%9A%D0%BE%D0%BF%D1%96%D1%8F_%D0%B7%D0%B0%D0%BF%D0%B8%D1%81%D0%BD%D0%B8%D0%BA%D0%B0_%22HW_%D0%9C%D0%B0%D1%82%D0%B5%D0%BC%D0%B0%D1%82%D0%B8%D1%87%D0%BD%D0%B5_%D1%84%D0%BE%D1%80%D0%BC%D1%83%D0%BB%D1%8E%D0%B2%D0%B0%D0%BD%D0%BD%D1%8F_%D0%BB%D0%BE%D0%B3%D1%96%D1%81%D1%82%D0%B8%D1%87%D0%BD%D0%BE%D1%97_%D1%80%D0%B5%D0%B3%D1%80%D0%B5%D1%81%D1%96%D1%97_ipynb%22.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

В цьому домашньому завданні ми реалізуємо логістичну регресію на `numpy`.
Ці завдання допоможуть вам ґрунтовно засвоїти основні концепції логістичної регресії та реалізувати їх на практиці 🔥

#### Завдання 1: Реалізація функції сигмоїди
1. З використанням `numpy` напишіть функцію `sigmoid(z)` для обчислення значення сигмоїди згідно з формулою:
   $$
   \sigma(z) = \frac{1}{1 + e^{-z}}
   $$
2. Використовуючи цю функцію, обчисліть значення сигмоїди для наступних даних: $ z = [-2, -1, 0, 1, 2] $. Виведіть результат обчислень.


In [1]:
import numpy as np

def sigmoid(z):
  return 1 / (1+ np.exp(-z))


In [4]:
z = np.array([-2, -1, 0, 1, 2])
sigmoid(z).round(4)

array([0.1192, 0.2689, 0.5   , 0.7311, 0.8808])



#### Завдання 2: Реалізація функції гіпотези для логістичної регресії
1. Напишіть функцію `hypothesis(theta, X)`, яка обчислює гіпотезу для логістичної регресії, використовуючи функцію сигмоїди. Формула гіпотези:
   $$
   h_\theta(x) = \sigma(\theta^T x) = \frac{1}{1 + e^{-\theta^T x}}
   $$
2. Використайте функцію `hypothesis` для обчислення значень гіпотези для наступних даних:
   
   $\theta = [0.5, -0.5]$
   
   $X = \begin{bmatrix} 1 & 2 \\ 1 & -1 \\ 1 & 0 \\ 1 & 1 \end{bmatrix}$

  Виведіть результат обчислень.


In [5]:
def hypothesis(theta, X):
    return sigmoid(np.dot(X, theta))

theta = np.array([0.5, -0.5])
X = np.array([[1, 2], [1, -1], [1, 0], [1, 1]])
hypothesis(theta, X)


array([0.37754067, 0.73105858, 0.62245933, 0.5       ])

#### Завдання 3: Реалізація функції для підрахунку градієнтів фукнції втрат
1. Напишіть функцію `compute_gradient(theta, X, y)`, яка обчислює градієнти функції втрат для логістичної регресії. Формула для обчислення градієнта:
   $$
   \frac{\partial L(\theta)}{\partial \theta_j} = \frac{1}{m} \sum_{i=1}^{m} \left[ (h_\theta(x^{(i)}) - y^{(i)}) x_j^{(i)} \right]
   $$
2. Використайте функцію `compute_gradient` для обчислення градієнтів для наступних даних:

  $\theta = [0.5, -0.5]$

  $X = \begin{bmatrix} 1 & 2 \\ 1 & -1 \\ 1 & 0 \\ 1 & 1 \end{bmatrix}$

  $y = [1, 0, 1, 0]$

  Виведіть результат обчислень.

In [6]:
def compute_gradient(theta, X, y):
    m = len(y)
    h = hypothesis(theta, X)
    gradient = (1 / m) * np.dot(X.T, (h - y))
    return gradient

theta = np.array([0.5, -0.5])
X = np.array([[1, 2], [1, -1], [1, 0], [1, 1]])
y = np.array([1, 0, 1, 0])

compute_gradient(theta, X, y)

array([ 0.05776464, -0.36899431])


#### Завдання 4: Реалізація повного батч градієнтного спуску

**Задача:**
1. Напишіть функцію `full_batch_gradient_descent(X, y, lr=0.1, epochs=100)`, яка реалізує алгоритм Full градієнтного спуску для логістичної регресії. Використовуйте такі формули:
   - Гіпотеза: $ h_\theta(x) = \sigma(\theta^T x) $
   - Оновлення параметрів: $ \theta_j := \theta_j - \alpha \frac{\partial L(\theta)}{\partial \theta_j} $
2. Використайте функцію `full_batch_gradient_descent` для обчислення параметрів моделі на наступних даних:

  $X = \begin{bmatrix} 1 & 2 \\ 1 & -1 \\ 1 & 0 \\ 1 & 1 \end{bmatrix}$

  $y = [1, 0, 1, 0]$

  Увага! Матриця $X$ вже має стовпець одиниць і передбачається, що це. - стовпець для intercept - параметра зсуву.

  Виведіть результат обчислень.


In [7]:
def full_batch_gradient_descent(X, y, lr=0.1, epochs=100):
    theta = np.zeros(X.shape[1])
    for _ in range(epochs):
        gradient = compute_gradient(theta, X, y)
        theta -= lr * gradient
    return theta

# Test the function
full_batch_gradient_descent(X, y)

array([-0.2893693 ,  0.77655125])

In [9]:
theta_final = full_batch_gradient_descent(X, y)

#### Завдання 5. Обчислення точності моделі

1. Напишіть функцію `predict_proba(theta, X)`, яка використовує знайдені параметри $\theta$ для обчислення ймовірностей належності поточного прикладу з даних до класу $y=1$ на основі значень $\sigma(\theta^T x)$.

2. Напишіть функцію `predict(theta, X, threshold=0.5)`, яка обчислює клас з передбаченої імовірності належності екземпляра до класу 1 з порогом 0.5. Тобто якщо ймовірність менше 0.5, то передбачаємо клас 0, інакше клас 1.

3. Напишіть функцію `accuracy(y_true, y_pred)`, яка обчислює точність моделі, визначивши частку правильно передбачених класів.

  Формула метрики Accuracy:
  $$
  \text{Accuracy} = \frac{\sum_{i=1}^{m} I(\hat{{y}^{(i)}} = y^{(i)})}{m}
  $$

  де $\hat{{y}^{(i)}}$ - передбачене значення класу, $I$ - індикаторна функція (яка дорівнює 1, якщо умова виконується, і 0 - якщо ні), $m$ - кількість прикладів.

4. Обчисліть з використанням даних в завданні 4 $X$, $y$ та обчислених коефіцієнтах $\theta$ та виведіть на екран:
  - передбачені моделлю імовірності належності кожного з екземплярів в матриці `X` до класу 1
  - класи кожного екземпляра з матриці `X`
  - точність моделі.

In [10]:
def predict_proba(theta, X):
    return hypothesis(theta, X)

def predict(theta, X, threshold=0.5):
    probabilities = predict_proba(theta, X)
    return (probabilities >= threshold).astype(int)

def accuracy(y_true, y_pred):
    return np.mean(y_true == y_pred)

# Test the functions
probabilities = predict_proba(theta_final, X)
predicted_classes = predict(theta_final, X)
model_accuracy = accuracy(y, predicted_classes)

print("Predicted probabilities:", probabilities)
print("Predicted classes:", predicted_classes)
print("Model accuracy:", model_accuracy)


Predicted probabilities: [0.77966809 0.25617965 0.42815828 0.61944235]
Predicted classes: [1 0 0 1]
Model accuracy: 0.5


Так, як точність моделі 0,5 трохи замала, то я запитала як можна виправити це і чат запропонував спроувати змінити к-сть епох та швидкість навчання

In [11]:
import numpy as np

def sigmoid(z):
    return 1 / (1 + np.exp(-z))

def hypothesis(theta, X):
    return sigmoid(np.dot(X, theta))

def compute_gradient(theta, X, y):
    m = len(y)
    h = hypothesis(theta, X)
    gradient = (1 / m) * np.dot(X.T, (h - y))
    return gradient

def full_batch_gradient_descent(X, y, lr=0.01, epochs=1000):
    theta = np.zeros(X.shape[1])
    for epoch in range(epochs):
        gradient = compute_gradient(theta, X, y)
        theta = theta - lr * gradient
    return theta

# Дані
X = np.array([[1, 2], [1, -1], [1, 0], [1, 1]])
y = np.array([1, 0, 1, 0])

# Навчання
theta = full_batch_gradient_descent(X, y, lr=0.01, epochs=1000)
print("Learned parameters (theta):", theta)

# Обчислення передбачених ймовірностей
def predict_proba(theta, X):
    return hypothesis(theta, X)

# Обчислення передбачених класів
def predict(theta, X, threshold=0.5):
    return (predict_proba(theta, X) >= threshold).astype(int)

# Обчислення точності
def accuracy(y_true, y_pred):
    return np.mean(y_true == y_pred)

# Передбачення
probabilities = predict_proba(theta, X)
predicted_classes = predict(theta, X)
accuracy_value = accuracy(y, predicted_classes)

print("Predicted probabilities:", probabilities)
print("Predicted classes:", predicted_classes)
print("Model accuracy:", accuracy_value)


Learned parameters (theta): [-0.28810244  0.774774  ]
Predicted probabilities: [0.77927485 0.25676015 0.42846849 0.61932202]
Predicted classes: [1 0 0 1]
Model accuracy: 0.5


Не змінилось, тому ймовірніше за все моделі потрібно більше даних для того, щоб покращити точність.

Створення 1 функції, яка буде рахувати все разом.

In [12]:
import numpy as np

def logistic_regression(X, y, lr=0.1, epochs=100):
    # Ініціалізація параметрів
    theta = np.zeros(X.shape[1])
    m = len(y)

    # Функція сигмоїди
    def sigmoid(z):
        return 1 / (1 + np.exp(-z))

    # Гіпотеза логістичної регресії
    def hypothesis(theta, X):
        return sigmoid(np.dot(X, theta))

    # Функція втрат (Cross-Entropy Loss)
    def compute_loss(theta, X, y):
        h = hypothesis(theta, X)
        loss = -np.mean(y * np.log(h) + (1 - y) * np.log(1 - h))
        return loss

    # Градієнт функції втрат
    def compute_gradient(theta, X, y):
        h = hypothesis(theta, X)
        gradient = np.dot(X.T, (h - y)) / m
        return gradient

    # Оновлення параметрів (Gradient Descent)
    for epoch in range(epochs):
        gradient = compute_gradient(theta, X, y)
        theta = theta - lr * gradient

    # Передбачення класів
    def predict_classes(theta, X, threshold=0.5):
        return (hypothesis(theta, X) >= threshold).astype(int)

    # Точність моделі
    def accuracy(y_true, y_pred):
        return np.mean(y_true == y_pred)

    # Обчислення передбачень та точності
    predicted_classes = predict_classes(theta, X)
    acc = accuracy(y, predicted_classes)

    return theta, acc

# Приклад використання
X = np.array([[1, 2], [1, -1], [1, 0], [1, 1]])
y = np.array([1, 0, 1, 0])
theta, accuracy = logistic_regression(X, y)
print("Learned parameters (theta):", theta)
print("Model accuracy:", accuracy)


Learned parameters (theta): [-0.28810244  0.774774  ]
Model accuracy: 0.5


Функція, яка дозводить ввести нові дані після запуску, без будь якого редагування коду.

In [22]:
import numpy as np

def logistic_regression(X, y, lr=0.1, epochs=100):
    # Реалізація логістичної регресії
    theta = np.zeros(X.shape[1])  # Ініціалізація параметрів моделі
    m = len(y)  # Кількість прикладів у наборі даних

    for epoch in range(epochs):
        h = 1 / (1 + np.exp(-np.dot(X, theta)))  # Гіпотеза логістичної регресії
        gradient = (1 / m) * np.dot(X.T, (h - y))  # Обчислення градієнту
        theta -= lr * gradient  # Оновлення параметрів за градієнтним спуском

    # Обчислення точності моделі
    y_pred = (1 / (1 + np.exp(-np.dot(X, theta)))) >= 0.5
    accuracy = np.mean(y_pred == y)

    return theta, accuracy

def main():
    # Введення даних з командного рядку
    print("ДЛЯ ЗУПИНКИ ВВЕДЕННЯ НАТИСНІТЬ 'enter' ПРИ ПУСТИХ ЗНАЧЕННЯХ. Введіть дані для матриці X (кожен рядок на новому рядку, значення розділяються пробілами): ")

    X = []
    while True:
        row = input().strip()
        if not row:
            break
        row = list(map(float, row.split()))
        X.append(row)
    X = np.array(X)

    # Введення даних для вектора y
    print("Введіть значення для вектора y (значення розділяються пробілами):")
    y = list(map(int, input().split()))

    # Виклик функції logistic_regression для надання передбачення
    try:
        theta, accuracy = logistic_regression(X, np.array(y))
        print(f"Передбачений клас: {theta}")
        print(f"Точність моделі: {accuracy}")
    except Exception as e:
        print(f"Виникла помилка: {str(e)}")

if __name__ == "__main__":
    main()


ДЛЯ ЗУПИНКИ ВВЕДЕННЯ НАТИСНІТЬ 'enter' ПРИ ПУСТИХ ЗНАЧЕННЯХ. Введіть дані для матриці X (кожен рядок на новому рядку, значення розділяються пробілами): 
1 3
1 2
1 -1

Введіть значення для вектора y (значення розділяються пробілами):
2 3 4
Передбачений клас: [20.38997815 13.24842006]
Точність моделі: 0.0
